spring.application.name=hello-world

# Database Connection
Spring.datasource.url=jdbc:postgresql://localhost:5432/todo
Spring.datasource.driverclassname=org.postgresql.Driver
Spring.datasource.username=postgres
Spring.datasource.password=yaanai12345



# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Optional (recommended)
spring.jpa.properties.hibernate.format_sql=true

spring.Security.user.name=admin
spring.Security.user.password=admin123


jwt.secret=abcdefghijklmnopqrstuvwxyz123456
jwt.expiration=3600000